library(ncdf4)
# csvpath <- "/Volumes/dongmeic/beetle/data/text/wus10km_v1/"
# ncpath <- "/Volumes/dongmeic/beetle/data/raster/wus10km_v1/"
csvpath <- "/Users/dongmeichen/Documents/beetle/csvfiles/"
ncpath <- "/Users/dongmeichen/Documents/beetle/ncfiles/"
#csvfile <- "wus10km_v1_short_01.csv"
csvfile <- "mpb10km.csv"

# open points netCDF file to get dimensions, etc.
ncin <- nc_open(paste(ncpath,"mpb10km_grid.nc",sep=""))
x <- ncvar_get(ncin, varid="x"); nx <- length(x)
y <- ncvar_get(ncin, varid="y"); ny <- length(y)
lon <- ncvar_get(ncin, varid="lon")
lat <- ncvar_get(ncin, varid="lat")
nc_close(ncin)

# time
year <- 1997:2013
nt <- length(year)
tunits <- "year"

# define dimensions
xdim <- ncdim_def("x",units="m",longname="x coordinate of projection",as.double(x))
ydim <- ncdim_def("y",units="m",longname="y coordinate of projection",as.double(y))
tdim <- ncdim_def("year",units=tunits,longname="year",as.integer(year))

# define common variables
fillvalue <- 1e32
dlname <- "Longitude of cell center"
lon_def <- ncvar_def("lon","degrees_east",list(xdim,ydim),NULL,dlname,prec="double")
dlname <- "Latitude of cell center"
lat_def <- ncvar_def("lat","degrees_north",list(xdim,ydim),NULL,dlname,prec="double")
projname <- "lambert_azimuthal_equal_area"
proj_def <- ncvar_def(projname,"1",NULL,NULL,longname=dlname,prec="char")
dlname <- "year"
time_def <- ncvar_def(dlname,tunits,list(tdim),NULL,dlname,prec="integer")

# read and reshape
indata <- read.csv(paste(csvpath, csvfile, sep=""))
str(indata)

j2 <- sapply(indata$x, function(xy) which.min(abs(x-xy)))
k2 <- sapply(indata$y, function(xy) which.min(abs(y-xy)))
head(cbind(indata$x,indata$y,j2,k2))

nobs <- dim(indata)[1]
m <- rep(1:nt,each=nobs)
temp_array <- array(fillvalue, dim = c(nx,ny,nt))
temp_array[cbind(j2,k2,m)] <- as.matrix(indata[1:nobs,38:54])  

# create netCDF file and put data
ncfname <- paste(ncpath,"mpb10km.nc", sep="")
dunits <- "binary"
var_def <- ncvar_def("btlfir_prs", dunits, list(xdim, ydim, tdim), fillvalue,"beetle and fire cooccurence in western US", prec="float")
ncout <- nc_create(ncfname,list(lon_def,lat_def,var_def,proj_def),force_v4=TRUE, verbose=FALSE)
ncvar_put(ncout, var_def, temp_array)

# put additional attributes into dimension and data variables
ncatt_put(ncout,"x","axis","X")
ncatt_put(ncout,"x","standard_name","projection_x_coordinate")
ncatt_put(ncout,"x","grid_spacing","10000 m")
ncatt_put(ncout,"x","_CoordinateAxisType","GeoX")
ncatt_put(ncout,"y","axis","Y")
ncatt_put(ncout,"y","standard_name","projection_y_coordinate")
ncatt_put(ncout,"y","grid_spacing","10000 m")
ncatt_put(ncout,"y","_CoordinateAxisType","GeoY")

ncatt_put(ncout,projname,"name",projname)
ncatt_put(ncout,projname,"long_name",projname)
ncatt_put(ncout,projname,"grid_mapping_name",projname)
ncatt_put(ncout,projname,"longitude_of_projection_origin",-112.5)
ncatt_put(ncout,projname,"latitude_of_projection_origin",45.0)
ncatt_put(ncout,projname,"_CoordinateTransformType","Projection")
ncatt_put(ncout,projname,"_CoordinateAxisTypes","GeoX GeoY")
na10km_projstr <- "+proj=laea +lon_0=-100 +lat_0=50 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"
ncatt_put(ncout,projname,"CRS.PROJ.4",na10km_projstr)

# put variables
ncvar_put(ncout,lon_def,lon)
ncvar_put(ncout,lat_def,lat)

# add global attributes
ncatt_put(ncout,0,"title","Yearly beetle presence onto the mpb10km 10-km Grid")
ncatt_put(ncout,0,"institution","Dept. Geography; Univ_ Oregon")
#ncatt_put(ncout,0,"source","generated by wus10km_v1_ncfiles_3d_02.R")
ncatt_put(ncout,0,"source","generated by cooccurrence.R")
history <- paste("D.Chen", date(), sep=", ")
ncatt_put(ncout,0,"history",history)
ncatt_put(ncout,0,"base_period","1997-2013")

# add more presence variables
varlist <- c("fire", "mpb")
for (i in 1:length(varlist)){
  varnm = paste(varlist[i], "_prs", sep="")
  varlnm = paste(varlist[i], " presence in western US", sep="")
  var_def <- ncvar_def(varnm, dunits, list(xdim, ydim, tdim), fillvalue,varlnm, prec = "float")
  ncout <- ncvar_add(ncout, var_def)
  temp_array <- array(fillvalue, dim = c(nx,ny,nt))
  temp_array[cbind(j2,k2,m)] <- as.matrix(indata[1:nobs,(4+nt*(i-1)):(3+nt*i)])  
  ncvar_put(ncout, var_def, temp_array)
}

# close the file, writing data to disk
nc_close(ncout)